version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"    # Jaeger UI
      # - "4318:4318"      # OTLP HTTP trace 수신

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0 
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"   # gRPC (trace + metrics)
      - "4318:4318"   # HTTP (추후 JS trace 등)
      - "9464:9464"   # Prometheus scrape

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
