receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  otlphttp:
    endpoint: http://jaeger:4318  # Jaeger가 OTLP HTTP로 수신

  prometheus:
    endpoint: "0.0.0.0:9464"

  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      exporters: [logging]